### ISSUE TITLE
Feature Request: Whois IP/domain Lookup capability in Network Flows

### ISSUE THREAD

**Issue by RudyAlbertoAcostaMarmalade** [firewalla/firewalla#1093]
Would it be possible to add a Whois IP/domain Lookup capability in much the same way as you have implemented the Security Intelligence section on Malicious sites i.e via a 3rd party website? This would be useful when browsing the Network Flows section and deciding if a blocking rule should be applied.

**Comment by MelvinTo** [comment]
Thanks for the feedback, it looks very reasonable. Will add to our todo list.

**Comment by RudyAlbertoAcostaMarmalade** [comment]
Hi, it's been over a year and I was wondering if this feature will actually be implemented? I spend a considerable amount of time having to look up the whois information of certain IP's - usually those that trigger upload alerts from my server estate - this is made difficult because I am operating within a mobile OS. Really hoping it makes it to the next release. Regards

**Comment by nnsense** [comment]
I was about to open the same request: +1!

**Comment by RudyAlbertoAcostaMarmalade** [comment]
It looks as though this has made it into the latest Alpha release - Firewalla Box Release 1.970 , iOS 1.37, Android 3.1 (Blue and Red only).

Thank you! Better late than never! ;)
