### ISSUE TITLE
Raspberry Pi with Ubuntu Image is running all services but iOS app never finds it?

### ISSUE THREAD

**Issue by techyowl** [firewalla/firewalla#1129]
I just finished setting up my raspberry Pi 3 b+ with Ubuntu 16 and I first created a new user of Pi since a lot of the buildraw4 script uses that. I first tried to use the plain build raw but noticed it's rather out of date. The brofish service is running and the firewalla service starts up and runs a ton of Sudo commands and then starts several other firewalla services that stay running like the firewalla main service and the firewalla api etc. however the iOS app on an iPhone 10 never sees the firewalla. I'm wondering does it still use Bluetooth or some sort of network scanning to find it now? I'm a backer of the firewalla blue but was hoping to get it up and running on a raspberry Pi for the time being. Now it appears to just be a networking issue between the firewalla app and release 6 on the raspberry Pi.

**Comment by techyowl** [comment]
I found out you guys switched to using bonjour for discovery so I started scanning for bonjour devices. My iMac connected via Ethernet to the router finds the firewalla bootingNNN where N is a digital generated on boot. My iPhone does not discover it for some reason even though it's on the same WiFi and can discover other devices such as my printers via the discovery bonjour scanning app. I found the firekickui log that just spits out infinitely several QR codes. Still not sure why my iPhone X won't find it.

**Comment by techyowl** [comment]
The bonjour device of firewalla booting adds to the network and then gets marked as removed from the networks few seconds later. I'm not finding anything relevant in any logs just a lot of FWDEBUG is in Production echoed several placeses

**Comment by jerrchen** [comment]
A bit of history, we started all of our work on the Raspberry Pi.   And the reason we paused that platform is, it is just too expensive to make a full product with that board.   This is the reason you see the code as it is today.    The Raspberry pi platform is pretty much 2 years behind, so it is not going to be easy to bring it up again.  (Both the control path and data path).

If you are interested, the best way is to use the blue.  We will try to setup a beta program before final release (please watch out for announcements from Indiegogo)

**Comment by techyowl** [comment]
I guess I will wait till the Blue launches beta then probably best to just wait then. And yeah I was surprised they haven't made a new raspberry Pi board in a while. Oh well it was worth a shot to try to get it running. I definitely want to be on that beta program when available.
