### ISSUE TITLE
Customer:  Need to handle or protect against /8 networks

### ISSUE THREAD

**Issue by jerrchen** [firewalla/firewalla#1158]
This is report in case 2207, where customer network is /8; this causes firewalla to allocate too much memory for device discovery... which eventually reboot due to lack of RAM.  We should advice customers to use /24 if possible.

**Comment by MelvinTo** [comment]
code added to suspend device discovery on /8
https://github.com/firewalla/firewalla/commit/7eec8fd66dba994f78b3ce648da16b8066d55388

code added to scan /24 instead of /8
https://github.com/firewalla/firewalla/commit/03c1663c686fad6ce29bf191fd58345b9d160d3f
