### ISSUE TITLE
redis.service does not exist

### ISSUE THREAD

**Issue by simora** [firewalla/firewalla#1166]
redis.service does not exist. this needs to be updated to redis-server.service.

https://github.com/firewalla/firewalla/blob/42d249a34177d33ea1c0bd01b69badec8a150ca5/etc/firewalla.service#L4

**Comment by simora** [comment]
This issue exists in firewalla.service file as well as fireupgrade.service file

**Comment by simora** [comment]
fixing those broken references to non-existent services allows all services to operate correctly.

using the following prevents fireupgrade from breaking those fixes. now my logs are filled with the happy spam of "Waiting for first app to connect..."

if [[ -e "/home/pi/.firewalla/config/.no_auto_upgrade" ]]; then

**Comment by simora** [comment]
submitted pr #1168 to solve issue. please merge at your earliest convenience so i can enable automagic updates.

**Comment by MelvinTo** [comment]
Thanks for the info. Both redis.service and redis-server.service are usable in our ubuntu image. So I'll merge your commit.

Thanks for the contribution. Cheers!

Melvin
