### ISSUE TITLE
Incorrect path

### ISSUE THREAD

**Issue by simora** [firewalla/firewalla#1178]
Should the line listed there read /home/pi/firewalla/scripts/fire-ping.sh ?

https://github.com/firewalla/firewalla/blob/f57c5c47d4a592ba3af82b0566f6b299b0caf07b/etc/brotab#L7

**Comment by MelvinTo** [comment]
This is intentional. When starting up, several critical scripts including fire-ping.sh will be copied to /home/pi/scripts so that they can still be used even if the git repository (/home/pi/firewalla) is somehow corrupted.
