### ISSUE TITLE
Bro is not installed in aarch64

### ISSUE THREAD

**Issue by simora** [firewalla/firewalla#1186]
How is bro installed if the lines are commented out? I imagine in your aarch64 or blue platform image you have bro installed in the base image?

https://github.com/firewalla/firewalla/blob/d760ce85935c6205c838869f626f02ffb3e985e8/buildraw_aarch64.sh#L120

**Comment by MelvinTo** [comment]
The bro package will be natively built-in when the blue image is released.

You can also compile and build by yourself.
https://github.com/bro/bro

We will use version 2.5.5
