### ISSUE TITLE
Can't run lastest source on Docker

### ISSUE THREAD

**Issue by dateno1** [firewalla/firewalla#1383]
Download lastest(1.958) source from here and build on docker it can't run

it seem can't find 'nslookup'

even i add busybox for this commnd and edit script it print another error message

is this tested before release?

**Comment by jerrchen** [comment]
The docker image is no longer supported.  It was used for quicker development, but at the moment, we more and more rely on the firewalla/red/blue for development, kind of abandoned this effort.   We just don't have the bandwidth to handle multiple platforms, this include the raspberry as well
