### ISSUE TITLE
Error: Failed to install node source repo on Raspi

### ISSUE THREAD

**Issue by heydemar** [firewalla/firewalla#1427]
I have this Error, has anybody a solution?

pi@raspberrypi:~ $ git clone https://github.com/firewalla/firewalla --branch release_pi_1_0 --single-branch
Cloning into 'firewalla'...
remote: Enumerating objects: 264, done.
remote: Counting objects: 100% (264/264), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 3204 (delta 254), reused 253 (delta 253), pack-reused 2940
Receiving objects: 100% (3204/3204), 42.05 MiB | 2.32 MiB/s, done.
Resolving deltas: 100% (2076/2076), done.
Checking connectivity... done.
pi@raspberrypi:~ $ cd firewalla
pi@raspberrypi:~/firewalla $ ./buildraw
Already up-to-date.
Installing node source repository...

================================================================================
================================================================================

                              DEPRECATION WARNING                            

  Node.js 4.x LTS Argon is no longer actively supported!

  You will not receive security or critical stability updates for this version.

  You should migrate to a supported version of Node.js as soon as possible.
  Use the installation script that corresponds to the version of Node.js you
  wish to install. e.g.

   * https://deb.nodesource.com/setup_8.x — Node.js 8 LTS "Carbon" (recommended)
   * https://deb.nodesource.com/setup_10.x — Node.js 10 Current

  Please see https://github.com/nodejs/Release for details about which
  version may be appropriate for you.

  The NodeSource Node.js distributions repository contains
  information both about supported versions of Node.js and supported Linux
  distributions. To learn more about usage, see the repository:
    https://github.com/nodesource/distributions

================================================================================
================================================================================

Continuing in 20 seconds ...

## You appear to be running on ARMv6 hardware. Unfortunately this is not currently supported by the NodeSource Linux distributions. Please use the 'linux-armv6l' binary tarballs available directly from nodejs.org for Node.js 4 and later.

Failed to install node source repo

**Comment by jerrchen** [comment]
The raspberry pi unfortunately is not supported now.  Even if you bring it up, the platform likely not to fully run.  The reason is ... we just don't have the time to make everything work
