### ISSUE TITLE
porn alarm not always happen

### ISSUE THREAD

**Issue by jerrchen** [firewalla/firewalla#199]
there is record of porn in old alarm but not in new alarm system. no new alert generated on phone

**Comment by MelvinTo** [comment]
same alarm will only generate once per 24 hours.

**Comment by jerrchen** [comment]
that's too long, use a smaller number.  If the kid is playing games several sessions a day ...  either

1. reduce that to (x) minutes
2. or send only after the initial one is cleared (or seen by the user)

for initial realse, 1 is better

**Comment by MelvinTo** [comment]
See commit 9be09a1d6144c1d4d14ee47a382b8a50a6879efd
