### ISSUE TITLE
Unhandled Rejects

### ISSUE THREAD

**Issue by jerrchen** [firewalla/firewalla#200]
When tap on the graph on first page, to get a summary

"2601:646:9100:c55::ac6f","198":"2601:646:9100:c55::44b0","199":"192.168.2.201","level":"info","message":"Summarize 0.0.0.0","timestamp":"2017-06-13T02:53:22.887Z"}
{"_bitField":18087936,"_fulfillmentHandler0":{},"level":"info","message":"Oh No! Unhandled rejection!! \nr:: [_Error: host is null] \ne::_","timestamp":"2017-06-13T02:53:22.952Z"}

Got unhandled rejects, seems the 

  // no parameters accepted
  getStats2(host) {
    if(!host)
      return Promise.reject(new Error("host is null"));

**Comment by jerrchen** [comment]
@MelvinTo  Bug is here, the getStats2 code need to take care when ip is 0.0.0.0, which should be all hosts

          // getStats2 => load 24 hours download/upload trend
          flowManager.getStats2(host)
            .then(() => {
//            flowManager.summarizeBytes2(hosts, Date.now() / 1000 - 60*60*24, -1,'hour', (err, sys) => {
//                log.info("Summarized devices: ", msg.data.end, msg.data.start, (msg.data.end - msg.data.start) / 16,sys,{});
                let jsonobj = {};
                if (host) {
                    jsonobj = host.toJson();
                }

**Comment by MelvinTo** [comment]
fixed. #202
