### ISSUE TITLE
Take down the whole network UBIQUITI EdgeRouter

### ISSUE THREAD

**Issue by yelwinsoe** [firewalla/firewalla#226]
Ubiquiti Models: ER‑X

Take down the whole network when try to turn off internet of an ip.

**Comment by MelvinTo** [comment]
Thanks for the feedback. Are you using the **release_pi_1_0** branch? Assume that you are running the software on raspberry pi.

**Comment by yelwinsoe** [comment]
Yes I am using release_pi_1_0 and it's on pi 3.

**Comment by jerrchen** [comment]
before turning off internet for ip, are you able to get other features working?  like looking at device and see what they are doing?  or minimum the traffic chart on top?

**Comment by jerrchen** [comment]
@MelvinTo if everything else work fine, likely be the block is still ip based not mac based in the old code causing trouble.

**Comment by yelwinsoe** [comment]
Everything work fine before I turn internet off to any ip. It seem it block the whole network when I block an ip including mobile device.

**Comment by jerrchen** [comment]
Great, the issue is likely a bug in that version of firewalla code.  Were you able to try out the adblock and family mode features?  Do they work?  Anyway, let us think a bit on how to deliver updates to that branch.  That branch is about 7 month behind.

**Comment by jerrchen** [comment]
@yelwinsoe are you good with linux?  If you are, we can give u instructions to update everything on the pi to latest code.   That may require linux / git

**Comment by yelwinsoe** [comment]
@jerrchen As i don't have iphone, having a bit problem testing for now, anyway if u can write down the instruction here I'll test later and update u guy. Thanks a lot.

**Comment by jerrchen** [comment]
How were able to control the device before without an iphone?    One other thought we have is to sell developer's units at low cost, is that something interesting to you?  It will be price of Raspberry pi + a small mark up to take care of logistics.

**Comment by yelwinsoe** [comment]
Sorry to replay u late. I would prefer android app since almost everyone own an android phone. Thanks anyway and going to close this issue for now.

**Comment by MelvinTo** [comment]
@yelwinsoe Android development is working in progress. If you are interested, we can invite you for beta use when it's ready.

**Comment by yelwinsoe** [comment]
@MelvinTo that would be great. Let me know. :)
