### ISSUE TITLE
Do not have qr code on raspberry pi

### ISSUE THREAD

**Issue by benguenter** [firewalla/firewalla#229]
I'm trying to get firewalla setup on my raspberry Pi but the iOS app is asking for a qr code. How do I connect without this code?

**Comment by jerrchen** [comment]
@benguenter Make sure you use raspberry pi 3, we do not support raspberry pi 2.  Reason is, the raspberry pi's has bluetooth 4.0, which we use to transmit the QR code.    This means, for you to bind to Firewalla, you have to stand close.  The binding is automatic.  

If you already have raspberry pi 3, make sure you turn on bluetooth on your iphone and stand close to the unit. 

enjoy

**Comment by benguenter** [comment]
Ah that was it. I am using a raspberry Pi 2 but I was able to connect a Bluetooth USB adapter. Then I set my phone close and waited about 5 minutes and it popped up.

**Comment by jerrchen** [comment]
I assume it worked.  This image is a bit old, there is 5 months of code behind it.  we will update it may be a bit later after we take care of stuff in kickstarter first.

**Comment by benguenter** [comment]
I used the latest image 1.74 I think from June 6th. Then followed the instructions in the readme. The instructions were a little out of date though. Such as the name of the iOS app. Confused me for a bit
