### ISSUE TITLE
Make VPN Logless

### ISSUE THREAD

**Issue by jerrchen** [firewalla/firewalla#230]
request from Ben

http://hack.training/create-logless-vpn/

**Comment by btrebach** [comment]
If you could use a hand with any part of this, please let me know - I'd be happy to help.

**Comment by jerrchen** [comment]
Super, we welcome all developers.   If you interested feel free to look at the VPN side.  Adding the logless is very simple, probably just a small modification of the vpn template
https://github.com/firewalla/firewalla/tree/master/vpn
The file to change is https://github.com/firewalla/firewalla/blob/master/vpn/server_config.txt
modify the server_config log into the log format specified in the link I posted.

**Comment by jerrchen** [comment]
@btrebach thank you for the commit, issue closed.

**Comment by hasanalizxc** [comment]
Hi All,

http://hack.training/create-logless-vpn/ is closed.. Can you give that article?

**Comment by jerrchen** [comment]
@hasanalizxc what article?

**Comment by r00t34** [comment]
I can't reach this website.

http://hack.training/create-logless-vpn/

Can you share it with me?
