### ISSUE TITLE
DoH + VPN

### ISSUE THREAD

**Issue by scafroglia93** [firewalla/firewalla#2694]
Could you use dns over https without losing the function once you are in the VPN?

Before installing firewalla I used nextdns and airvpn without any problem while now I'm forced to use either one or the other

**Comment by dkoppenh** [comment]
I believe forcing the DNS to use that of the VPN provider is desired behavior. It prevents leaking DNS requests to anyone other than your VPN provider.

**Comment by scafroglia93** [comment]
The totality of the dns provided by the vpn is not encrypted and makes useless solutions such as pihole or nextdns that allow you to encrypt requests and implement an additional security layer

Currently, several lists drawn up by National Cert for IT security converge within nextdns

**Comment by dkoppenh** [comment]
I thought once you connected to the VPN, all DNS requests were encrypted anyways because they were made through the VPN tunnel.

But I can see the utility of being able to choose whether you want DNS to use a separate provider or the VPN provider's.
