### ISSUE TITLE
turn off log2ram

### ISSUE THREAD

**Issue by jerrchen** [firewalla/firewalla#276]
log2ram maps 50M of ram.  Logs are rotated weekly and stay uncompressed in the /var/log directory.  When this happens, the /var/log directory will eventually explode, and no log can be written. (ever).   And we lost 50megs of memory

To fix this problem, 
solution 1:
Tune /var/log  such that log2ram maps to a directory that max can ever be is less than few megabytes.  And logrotate to somewhere else.

solution 2:
stop using log2ram and use what ever it is there.

**Comment by jimyang2008** [comment]
problem resolved with a recent commit in firewalla/utils, where it disable log2ram completely
