### ISSUE TITLE
memory usage is increasing

### ISSUE THREAD

**Issue by jerrchen** [firewalla/firewalla#329]
grep ",dns" memory.csv | awk -F ',' '{ x = x + $4 } END {print x}'
1716005
grep "aggrflow" memory.csv | awk -F ',' '{ x = x + $4 } END {print x}'
5834716
grep ",flow" memory.csv | awk -F ',' '{ x = x + $4 } END {print x}'
19810960
grep ",sumflow" memory.csv | awk -F ',' '{ x = x + $4 } END {print x}'
21820269
grep ",flow:conn" memory.csv | awk -F ',' '{ x = x + $4 } END {print x}'
10817228
grep ",flow:x509" memory.csv | awk -F ',' '{ x = x + $4 } END {print x}'
6970112

**Comment by jerrchen** [comment]
I have commited code to drop flow:x509 to very little.
sumflow is the biggest problem

**Comment by MelvinTo** [comment]
looks good now. no memory issue for a long time
