### ISSUE TITLE
*.cnzz.com should not be suspicious: all.cnzz.com.danuoyi.tbcache.com

### ISSUE THREAD

**Issue by starsy** [firewalla/firewalla#391]
It is Taobao CDN and most of the alarm is false positive. 

**As it is a wildcard domain name, can a wildcard whitelist be defined for it?**

$ ping s4.cnzz.com
PING all.cnzz.com.danuoyi.tbcache.com (223.82.136.219): 56 data bytes
Request timeout for icmp_seq 0
64 bytes from 223.82.136.219: icmp_seq=1 ttl=15 time=172.506 ms
^C
--- all.cnzz.com.danuoyi.tbcache.com ping statistics ---
2 packets transmitted, 1 packets received, 50.0% packet loss
round-trip min/avg/max/stddev = 172.506/172.506/172.506/0.000 ms
$ ping w.cnzz.com
PING all.cnzz.com.danuoyi.tbcache.com (223.82.136.219): 56 data bytes
64 bytes from 223.82.136.219: icmp_seq=0 ttl=14 time=187.277 ms
^C
--- all.cnzz.com.danuoyi.tbcache.com ping statistics ---
2 packets transmitted, 1 packets received, 50.0% packet loss
round-trip min/avg/max/stddev = 187.277/187.277/187.277/0.000 ms

![img_4254](https://user-images.githubusercontent.com/1459979/31324633-5f3f78d8-ac7a-11e7-871e-455a96e35d9f.PNG)

**Comment by MelvinTo** [comment]
cnzz.com是一收用户数据的网站，没有“安全隐患”，但是ban了减少隐私泄漏，也不会对用户体验有影响。

**Comment by MelvinTo** [comment]
cnzz被阿里收了，所以。。

**Comment by starsy** [comment]
The problem is I don’t want to see *.cnzz.com alarms as it seems to be false positives to me, but no way to allow them all at once.

**Comment by jerrchen** [comment]
Tap on ignore.  It may work

**Comment by starsy** [comment]
Too many sub domains under cnzz.com, need a way to allow/block them all. The same to *.amazonaws.com

**Comment by jerrchen** [comment]
The blocking feature for domains is there, probably need to be activated for alarms.    The allow one is going to be tricky.  but all can be done with good assitant from the cloud

**Comment by MelvinTo** [comment]
as workaround, you can block *.cnzz.com at flow section.

**Comment by MelvinTo** [comment]
block by domain is already supported in alarm interface
