### ISSUE TITLE
Allow/Block has different type for the same alarm

### ISSUE THREAD

**Issue by starsy** [firewalla/firewalla#425]
'ignore' =>  { 'i.type': '**domain**',
  aid: '11',
  reason: 'ALARM_INTEL',
  type: 'ALARM_INTEL',
  timestamp: 1508686478.174,
  'p.dest.id': '114.113.217.103',
  target_name: 'battle.net',
  target_ip: '114.113.217.103',
  eid: '46' }

'block' =>  { timestamp: 1508686514.815,
  type: '**ip**',
  target: '114.113.217.103',
  aid: '11',
  reason: 'ALARM_INTEL',
  target_name: 'battle.net',
  target_ip: '114.113.217.103',
  pid: '9' }

**Comment by MelvinTo** [comment]
this was done intentionally. The data structure for alarm/policy/exception is all different. Do not assume they are the same.
