### ISSUE TITLE
App: switch style is not so straight forward

### ISSUE THREAD

**Issue by xuanxuandog** [firewalla/firewalla#50]
currently, the switch style below is not so straight forward which may confuse user whether it's on or not:

![img_5915](https://cloud.githubusercontent.com/assets/22969387/20084705/13034842-a59f-11e6-97a6-0348ec8d57e5.PNG)

Something like below may be more straight forward

![img_5916](https://cloud.githubusercontent.com/assets/22969387/20084713/1cfee9b4-a59f-11e6-8db8-f2b6cfcf26d3.PNG)

**Comment by jerrchen** [comment]
made the button green.
