### ISSUE TITLE
[compatibility] UPNP NewLeaseDuration (impacting vpn)

### ISSUE THREAD

**Issue by jerrchen** [firewalla/firewalla#556]
Some routers (such as the netgear x6s ) will allow upnp settings, but not query ... it appears the router also only allow upnp setting of ttl = 0.

**Comment by jerrchen** [comment]
It may be this issue 

https://www.rfc-editor.org/rfc/rfc6886.txt
"
   In principle, UPnP IGD should allow clients to specify a lifetime on
   port mappings.  However, a Google search for "UPnP NewLeaseDuration"
   shows that in practice pretty much every client uses
   "<NewLeaseDuration>0</NewLeaseDuration>" to request an infinite
   lease, and the protocol has no way for the NAT gateway to decline
   that infinite lease request and require the client to renew it at
   reasonable intervals.  Furthermore, anecdotal evidence is that if the
   client requests a lease other than zero, there are IGD home gateways
   that will ignore the request, fail in other ways, or even crash
   completely.  As a client implementer then, you would be well advised
   not to attempt to request a lease other than zero, unless you want to
   suffer the support costs and bad publicity of lots of people
   complaining that your device brought down their entire network.
"

**Comment by MelvinTo** [comment]
set all upnp ttl to 0 via commit 8880190fb754c51f1d3fa3279c8aca9cf86c6d70
