### ISSUE TITLE
ssh random password should be more complex

### ISSUE THREAD

**Issue by MelvinTo** [firewalla/firewalla#601]
This issue was originally reported by user Wade Stadig. Thanks for the report.

8 chars long is too weak from security practice.

For detail information, please refer to original post:
https://help.firewalla.com/hc/en-us/community/posts/115003755094-Security-vulnerability-with-Firewalla?flash_digest=90c64dfed2412a2a4a056c70787ac2350a7c0115#

**Comment by jerrchen** [comment]
Password will somewhat look like this: Wq](j?gU2K   It will take (98)^10 possible combinations.    

Used to be (36)^8 or 2821109907456 tries to crack ...
