### ISSUE TITLE
Need to be able to turn off ssh

### ISSUE THREAD

**Issue by MelvinTo** [firewalla/firewalla#602]
This issue was originally reported by user Wade Stadig. Thanks for the report.

SSH server on Firewalla can't be turned off, need to be able to turn off to reduce security exposure.

For detail information, please refer to original post:
https://help.firewalla.com/hc/en-us/community/posts/115003755094-Security-vulnerability-with-Firewalla?flash_digest=90c64dfed2412a2a4a056c70787ac2350a7c0115#

**Comment by jerrchen** [comment]
This may be lesser of a risk since the ports that are open are inside consumer home.  This is no different than an HTTP port open to configure the router.  Re-enable our previous knob on the UI is probably useful.

**Comment by jerrchen** [comment]
Feedback from customer, this is a lower priority feature
"
Thanks for the quick responses/action! I'm loving my firewalla and appreciate the work you guys have put into this. Looking back I apologize that my comments came off strong. In hindsight I wish I would have worded it differently. 

Also, more importantly, I TOTALLY misunderstood how SSH was configured/working. I thought SSH was turned on to the external facing network. This basically renders all of my concerns totally moot. So yea... heh, apologies!
"

**Comment by jerrchen** [comment]
There is no need to turn off SSH.  Firewalla will not expose self to external services.  The SSH access purely internal.  To make SSH more clear, we have moved SSH to advanced settings. (rather than from support)
