### ISSUE TITLE
BUG: Devices awaken from long sleep don't automatically appear in app

### ISSUE THREAD

**Issue by MelvinTo** [firewalla/firewalla#623]
## How to reproduce
1. Add device to network, device will be detected by Firewalla
2. Disconnect device from network
3. Wait for more than 7 days, device will no longer appear in app (inactive device)
4. Add device back to network, device still does not appear in app, however in backend database, it's already detected.
5. Restart FireApi can fix this issue as workaround

**Note: This issue is originally found at Ricky's office.**

**Comment by jerrchen** [comment]
suspect something in the host manager db is not getting refreshed.  will look
