### ISSUE TITLE
[Production] device name mapping error

### ISSUE THREAD

**Issue by jerrchen** [firewalla/firewalla#627]
"When looking at the Devices screen in the iOS app, I see several devices that are duplicates. I assigned user-friendly names to my family's various devices, but sometimes when those devices rejoin the network (either after being out of the house or shut down), they are treated as brand new devices on the network. Seems like when a device acquires a new IP Firewalla considers it new. Would be it possible to recognize known devices by MAC address or something else that's constant?"

https://help.firewalla.com/hc/en-us/community/posts/115007773333-Better-Recognition-of-Known-Devices-When-Rejoining-a-Network

**Comment by jerrchen** [comment]
This is issue where iOS is trying to hide MAC address.  When this happens, iOS (iphone or pad) will use private MAC addresses randomly.  There is no way to get around this problem.

**Comment by MelvinTo** [comment]
this is because some devices were behind the wifi extender, which works like a network bridge. The wifi extender's MAC address will be used to link to each device. After he removed the extender, everything should be fine now.
