### ISSUE TITLE
Raspbian Jessie is no longer provided - now Raspbian Stretch is available

### ISSUE THREAD

**Issue by JonTheNiceGuy** [firewalla/firewalla#666]
Followed installation guide, noted that:

1. brofish service is running.
2. fireapi.service is disabled
3. firekick.service is running
4. firemain.service is running
5. firemon.service is running
6. fireui.service is disabled
7. firewalla.service may be disabled (I'd poked it already when I started looking), but fails to start due to missing ntp.service.

Installing ntp (`apt install -y ntp`), preventing it from running on boot (this seems to conflict with the firewalla.service? `systemctl disable ntp`) and then enabling the disabled services (`systemctl enable fireapi fireui firewalla`) did seem to resolve things.

**Comment by JonTheNiceGuy** [comment]
There is an alternate download location from http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2017-07-05/2017-07-05-raspbian-jessie-lite.zip which is the latest Jessie version I could find. I'm trying that image now to see if these images work themselves out as a result...

**Comment by jerrchen** [comment]
Jon, we are a bit behind on bringing up the Raspberry Pi version.  Will likely get back to it once we stabilize our official Hardware.  I think ubuntu 16.04 should work, one of our supporter got it working on that.

**Comment by JonTheNiceGuy** [comment]
Hi, sorry, I hope I didn't sound like I was complaining! I was trying to help! I can't afford to get the appliance, but I have an RPi board knocking around that I can use to try stuff out, and I'm just keen to help where I can!

**Comment by JonTheNiceGuy** [comment]
Ah. I honestly thought the RPi version didn't require a license purchase. That makes it a bit of a harder sell. Need to discuss finances with my wife then.

**Comment by jerrchen** [comment]
the RPi version does not need a license to run for sure.  It will be talking to our development/debug cloud server.  With a license, it will talk to the production cloud server.  So if u get a Firewalla box, the sticker below it will work with Raspberry pi as well.
