### ISSUE TITLE
Raspberry Pi image with Android - No QR code, apparently no bluetooth detection either?

### ISSUE THREAD

**Issue by JonTheNiceGuy** [firewalla/firewalla#667]
Hi,

I've stood up the Firewalla following the instructions in the readme (https://github.com/firewalla/firewalla/blame/master/README.md#L24-L57) and have filed a bug #666 (ominous!) about the Raspbian version currently available.

Having encouraged all the services to start (there's a missing dependency on ntp in stretch), I got the prompt to add the device, but it was only asking me for a QR code.

Pi devices could use the SSH connection to render a QR Code. See my code for an example, plus source link for how I found out about it:

https://gist.github.com/JonTheNiceGuy/294c5eadb3832c7bc6f90f472ca28242#file-ibeacon-sh-L126-L129

Also, I'm trying to use the latest Jessie version available to see if the Bluetooth element works then...

**Comment by AlMoselly** [comment]
is it still the same QR problem with Android version ?
can we connect to Raspberry using bluetooth to Android 

Best regards
