### ISSUE TITLE
Customer Request: DHCP Static

### ISSUE THREAD

**Issue by jerrchen** [firewalla/firewalla#730]
https://help.firewalla.com/hc/en-us/community/posts/360000527334-Able-to-assign-static-IP-within-firewalla?page=1#community_comment_360000181573

**Comment by starsy** [comment]
Work on Walla is done, require UI work. https://github.com/firewalla/firewalla/pull/825

**Comment by jerrchen** [comment]
Nice, we need to build the UI for this and port forward.    Lots of our customers want these
